version: '3.8'

volumes:
  shared-repos:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared-repos
  elasticsearch-data:

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Initialize shared volume permissions
  init-volume:
    image: alpine:latest
    volumes:
      - ./shared-repos:/shared/heimdall-repos
    command: |
      sh -c "
        mkdir -p /shared/heimdall-repos &&
        chown -R 1000:1000 /shared/heimdall-repos &&
        chmod -R 755 /shared/heimdall-repos
      "
    
  cloner:
    build:
      context: .
      dockerfile: deployments/cloner/Dockerfile
    volumes:
      - ./shared-repos:/shared/heimdall-repos
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_CONCURRENT_CLONES=5
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - SHARED_VOLUME_DIR=/shared/heimdall-repos
    depends_on:
      - redis
      - init-volume
    restart: unless-stopped

  collector:
    build:
      context: .
      dockerfile: deployments/collector/Dockerfile
    environment:
      - GITHUB_ORG=${GITHUB_ORG}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUN_ON_STARTUP=true
      - GITHUB_PAGE_SIZE=100
      - GITHUB_API_DELAY_MS=500
      - COLLECTION_SCHEDULE=${COLLECTION_SCHEDULE:-0 0 * * 0}
    depends_on:
      - redis
    restart: unless-stopped

  scanner:
    build:
      context: .
      dockerfile: deployments/scanner/Dockerfile
    volumes:
      - ./shared-repos:/shared/heimdall-repos
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_CONCURRENT_SCANS=3
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - SCAN_TIMEOUT_MINUTES=30
      - SHARED_VOLUME_DIR=/shared/heimdall-repos
      - PROCESSED_QUEUE_NAME=processed_queue
      - SECRETS_QUEUE_NAME=secrets_queue
      - CLEANUP_QUEUE_NAME=cleanup_queue
    depends_on:
      - redis
      - init-volume
    restart: unless-stopped

  cleaner:
    build:
      context: .
      dockerfile: deployments/cleaner/Dockerfile
    volumes:
      - ./shared-repos:/shared/heimdall-repos
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLEANUP_QUEUE_NAME=cleanup_queue
      - SHARED_VOLUME_DIR=/shared/heimdall-repos
      - MAX_CONCURRENT_JOBS=2
    depends_on:
      - redis
      - init-volume
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  indexer:
    build:
      context: .
      dockerfile: deployments/indexer/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - INDEX_NAME=heimdall-secrets
      - SECRETS_QUEUE_NAME=secrets_queue
      - MAX_CONCURRENT_WORKERS=2
      - BULK_SIZE=50
      - BULK_FLUSH_INTERVAL=10s
    depends_on:
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped