volumes:
  shared-repos:
    driver_opts:
      type: none
      o: bind
      device: ~/git
  elasticsearch-data:

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  # Initialize shared volume permissions
  init-volume:
    image: alpine:latest
    volumes:
      - ~/git:/shared/heimdall-repos
    command: |
      sh -c "
        mkdir -p /shared/heimdall-repos &&
        chown -R 1000:1000 /shared/heimdall-repos &&
        chmod -R 755 /shared/heimdall-repos
      "

  sync:
    build:
      context: .
      dockerfile: deployments/sync/Dockerfile
    volumes:
      - ~/git:/shared/heimdall-repos
    environment:
      - GITHUB_ORG=${GITHUB_ORG}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - REDIS_URL=redis://redis:6379
      - FETCH_ON_STARTUP=true
      - FETCH_SCHEDULE=${FETCH_SCHEDULE:-0 0 * * 0}
      - MAX_CONCURRENT_SYNCS=10
      - SYNC_TIMEOUT_MINUTES=30
      - SHARED_VOLUME_PATH=/shared/heimdall-repos
      - TRUFFLEHOG_QUEUE_NAME=trufflehog_queue
      - OSV_QUEUE_NAME=osv_queue
      - GITHUB_API_DELAY_MS=100
      - QUEUE_BATCH_SIZE=10
      # Scanner queue configuration
      - ENABLE_SCANNER_QUEUES=${ENABLE_SCANNER_QUEUES:-true}
      - ENABLE_TRUFFLEHOG_QUEUE=${ENABLE_TRUFFLEHOG_QUEUE:-true}
      - ENABLE_OSV_QUEUE=${ENABLE_OSV_QUEUE:-true}
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-stdout}
      - LOG_ADD_SOURCE=${LOG_ADD_SOURCE:-false}
    depends_on:
      - redis
      - init-volume
    restart: unless-stopped

  scanner-trufflehog:
    build:
      context: .
      dockerfile: deployments/scanner-trufflehog/Dockerfile
    volumes:
      - ~/git:/shared/heimdall-repos
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_CONCURRENT_SCANS=3
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - SCAN_TIMEOUT_MINUTES=30
      - SHARED_VOLUME_DIR=/shared/heimdall-repos
      - TRUFFLEHOG_QUEUE_NAME=trufflehog_queue
      - TRUFFLEHOG_RESULTS_QUEUE_NAME=trufflehog_results_queue
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-stdout}
      - LOG_ADD_SOURCE=${LOG_ADD_SOURCE:-false}
    depends_on:
      - redis
      - init-volume
    restart: unless-stopped


  scanner-osv:
    build:
      context: .
      dockerfile: deployments/scanner-osv/Dockerfile
    volumes:
      - ~/git:/shared/heimdall-repos
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_CONCURRENT_SCANS=3
      - SCAN_TIMEOUT_MINUTES=30
      - SHARED_VOLUME_DIR=/shared/heimdall-repos
      - OSV_QUEUE_NAME=osv_queue
      - OSV_RESULTS_QUEUE_NAME=osv_results_queue
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-stdout}
      - LOG_ADD_SOURCE=${LOG_ADD_SOURCE:-false}
    depends_on:
      - redis
      - init-volume
    restart: unless-stopped

  indexer:
    build:
      context: .
      dockerfile: deployments/indexer/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - INDEX_NAME=heimdall-secrets
      - VULNERABILITIES_INDEX_NAME=heimdall-vulnerabilities
      - TRUFFLEHOG_RESULTS_QUEUE_NAME=trufflehog_results_queue
      - OSV_RESULTS_QUEUE_NAME=osv_results_queue
      - MAX_CONCURRENT_WORKERS=2
      - BULK_SIZE=50
      - BULK_FLUSH_INTERVAL=10s
      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - LOG_OUTPUT=${LOG_OUTPUT:-stdout}
      - LOG_ADD_SOURCE=${LOG_ADD_SOURCE:-false}
    depends_on:
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
