{{- if .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-github
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc | quote }}
{{- end }}