name: Build and Push

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  SYNC_IMAGE_NAME: klimeurt/heimdall-sync
  SCANNER_TRUFFLEHOG_IMAGE_NAME: klimeurt/heimdall-scanner-trufflehog
  SCANNER_OSV_IMAGE_NAME: klimeurt/heimdall-scanner-osv
  INDEXER_IMAGE_NAME: klimeurt/heimdall-indexer

jobs:
  build-and-push-sync:
    name: Build and Push Sync Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract sync metadata
      id: sync-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.SYNC_IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest

    - name: Build and push Sync Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: deployments/sync/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.sync-meta.outputs.tags }}
        labels: ${{ steps.sync-meta.outputs.labels }}
        cache-from: type=gha,scope=sync
        cache-to: type=gha,mode=max,scope=sync
        annotations: |
          org.opencontainers.image.visibility=public

  build-and-push-scanner-trufflehog:
    name: Build and Push Scanner-TruffleHog Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract scanner-trufflehog metadata
      id: scanner-trufflehog-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.SCANNER_TRUFFLEHOG_IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest

    - name: Build and push Scanner-TruffleHog Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: deployments/scanner-trufflehog/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.scanner-trufflehog-meta.outputs.tags }}
        labels: ${{ steps.scanner-trufflehog-meta.outputs.labels }}
        cache-from: type=gha,scope=scanner-trufflehog
        cache-to: type=gha,mode=max,scope=scanner-trufflehog
        annotations: |
          org.opencontainers.image.visibility=public

  build-and-push-scanner-osv:
    name: Build and Push Scanner-OSV Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract scanner-osv metadata
      id: scanner-osv-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.SCANNER_OSV_IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest

    - name: Build and push Scanner-OSV Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: deployments/scanner-osv/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.scanner-osv-meta.outputs.tags }}
        labels: ${{ steps.scanner-osv-meta.outputs.labels }}
        cache-from: type=gha,scope=scanner-osv
        cache-to: type=gha,mode=max,scope=scanner-osv
        annotations: |
          org.opencontainers.image.visibility=public

  build-and-push-indexer:
    name: Build and Push Indexer Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract indexer metadata
      id: indexer-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.INDEXER_IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest

    - name: Build and push Indexer Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: deployments/indexer/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.indexer-meta.outputs.tags }}
        labels: ${{ steps.indexer-meta.outputs.labels }}
        cache-from: type=gha,scope=indexer
        cache-to: type=gha,mode=max,scope=indexer
        annotations: |
          org.opencontainers.image.visibility=public